/** @file
	@brief Config header with Fusion limit defines - Must be included before any
	Fusion header!

	Header AUTO-GENERATED by variadicGenerate.lua on input ArityConfig.gen.lua to ensure consistency

	DO NOT EDIT THIS FILE DIRECTLY - instead, edit the script that generates it.
	In this case, this file mostly exists to get constants used when generating
	_any_ file into one file to configure support libraries, so the generation
	script shared by all generated files contains the typically-interesting
	values.

	Note that only by editing and re-running the generating script can you
	change these limits, since some files are pre-generated instead of
	using BOOST_PP_...

	@author
	Ryan Pavlik
	<rpavlik@iastate.edu> and <abiryan@ryand.net>
	http://academic.cleardefinition.com/
	Iowa State University Virtual Reality Applications Center
	Human-Computer Interaction Graduate Program
*/

//          Copyright Iowa State University 2012.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#pragma once
#ifndef INCLUDED_FusionConfig_h_GUID_e185dc4f_3d12_4f22_ae37_ee131be6d12a
#define INCLUDED_FusionConfig_h_GUID_e185dc4f_3d12_4f22_ae37_ee131be6d12a

// Internal Includes
// - none

// Library/third-party includes
// - none

// Standard includes
// - none



#define FUSION_MAX_LIST_SIZE 9
#define BOOST_FUSION_INVOKE_PROCEDURE_MAX_ARITY 9
namespace transmission {
	namespace detail {
		namespace constants {
			enum {
				ReceiveMaxArity = 9
			};
		} // end of namespace constants
	} // end of namespace detail
} // end of namespace transmission

#endif // INCLUDED_FusionConfig_h_GUID_e185dc4f_3d12_4f22_ae37_ee131be6d12a

