return {
	outFile = "PartialHandlerBase.h";
	baseIndent = 3;
	minArity = ReceiveMinArity;
	maxArity = ReceiveMaxArity;

	generate = function(arity)
		-- Message type "tag" argument
		local argumentTypes = {"typename M"}
		local arguments = { "M const &" }

		-- Tuple values
		if arity > 0 then
			table.insert(argumentTypes, genRange(arity, function(i) return ("typename T%d"):format(i) end))
			table.insert(arguments, genRange(arity, function(i) return ("T%d"):format(i) end))
		end

		-- SFINAE test to ensure the first argument is actually a message type.
		table.insert(arguments, "typename M::message_type_tag * = NULL")

		-- SFINAE test to not gobble up Fusion sequences before we can split them up.
		if arity == 1 then
			table.insert(arguments, "typename boost::disable_if<boost::fusion::traits::is_sequence<T1> >::type * = NULL")
		end

		out(("template<%s>"):format(commaJoin(argumentTypes)))
		out(("void operator()(%s) {}\n"):format(commaJoin(arguments)))
	end;

	prefix = [[
/** @file
	@brief Header AUTO-GENERATED by %s to avoid doing crazy preprocessor things

	DO NOT EDIT THIS FILE DIRECTLY - instead, edit the script that generates it.

	@date 2012

	@author
	Ryan Pavlik
	<rpavlik@iastate.edu> and <abiryan@ryand.net>
	http://academic.cleardefinition.com/
	Iowa State University Virtual Reality Applications Center
	Human-Computer Interaction Graduate Program
*/

//          Copyright Iowa State University 2012.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#pragma once
#ifndef INCLUDED_PartialHandlerBase_h_GUID_314b3576_c339_42e9_ac75_cccb9b7f0bfe
#define INCLUDED_PartialHandlerBase_h_GUID_314b3576_c339_42e9_ac75_cccb9b7f0bfe

// Internal Includes
#include "Receiver.h"
#include "ParameterHandlerBase.h"

// Library/third-party includes
#include <boost/utility/enable_if.hpp>
#include <boost/fusion/include/is_sequence.hpp>

// Standard includes
// - none

namespace transmission {

	/** @brief Base class for use in creating functors for transmission::Receiver
		that provides default handlers for all message types.

		If you derive your functor from this class, you don't have to provide all
		the handlers, and you must include a line like the following in the
		functor to explicitly use the provided defaults:

		using transmission::PartialHandlerBase<YourClass>::operator();
	*/
	template<typename Derived>
	class PartialHandlerBase : public ParameterHandlerBase<Derived> {
		public:
			using ParameterHandlerBase<Derived>::operator();
]];

	suffix = [[
	};
} // end of namespace transmission

#endif // INCLUDED_PartialHandlerBase_h_GUID_314b3576_c339_42e9_ac75_cccb9b7f0bfe
]];
}
